# Generated by Django 4.1.5 on 2023-01-17 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0011_contato_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='usuario',
            new_name='user',
        ),
    ]
